= image-filters-4j

image:https://github.com/ghillert/image-filters-4j/actions/workflows/maven.yml/badge.svg?branch=main[Java CI with Maven, link="https://github.com/ghillert/image-filters-4j/actions/workflows/maven.yml"]

Image Processing Filters for Java

I did not see any Mavenized version of Jerry Huxtable's *Java Image Processing Classes*.

This repo contains all classes as available via the download at:

http://www.jhlabs.com/ip/filters/download.html

The goal is to have the filters available via the Maven Central repository eventually.

== Getting Started

=== Maven

To use the filters in your Maven project, add the following dependency to your `pom.xml`:

=== Usage

[source,java,indent=0]
----
    final ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
    final String imageResourcePath = "images/image-filters-4j.png";
    final BufferedImage originalBufferedImage;

    try (InputStream inputStream = classLoader.getResourceAsStream(imageResourcePath)) {
        if (inputStream == null) {
            throw new IllegalStateException("Resource not found: " + imageResourcePath);
        }
        originalBufferedImage = ImageIO.read(inputStream);
    }
    catch (IOException ex) {
        throw new IllegalStateException("Unable to read image at " + imageResourcePath, ex);
    }

    final BufferedImage grayscaleBufferedImage = new GrayscaleFilter().filter(originalBufferedImage, null);

    final Path outputPath = Path.of("target", "image-filters-4j_output.png");

    try {
        Files.createDirectories(outputPath.getParent());
        ImageIO.write(grayscaleBufferedImage, "png", outputPath.toFile());
    }
    catch (IOException ex) {
        throw new IllegalStateException("Unable to write image to " + outputPath, ex);
    }
----

== Maven Dependencies

Currently, snapshot releases are available via the following Maven repository:

[source,xml]
----
<repository>
  <id>snapshots-repo</id>
  <url>https://central.sonatype.com/repository/maven-snapshots</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
----

== List of Filters

The following filters are included in this library:

=== Color Adjustment Filters

[cols="6,1",options="header"]
|===
|Filter |New

|ChannelMixFilter |
|ContrastFilter |
|CurvesFilter |
|DiffusionFilter |
|DitherFilter |
|ExposureFilter |
|GainFilter |
|GammaFilter |
|GrayFilter |
|GrayscaleFilter |
|HSBAdjustFilter |
|InvertAlphaFilter |
|InvertFilter |
|LevelsFilter |
|LookupFilter |
|MapColorsFilter |
|MaskFilter |
|PosterizeFilter |
|QuantizeFilter |
|RescaleFilter |
|RGBAdjustFilter |
|SepiaFilter | ✅
|SolarizeFilter |
|ThresholdFilter |
|TritoneFilter |
|===

=== Distortion & Warping Filters

[cols="6,1",options="header"]
|===
|Filter |New

|BicubicScaleFilter |
|CircleFilter |
|CropFilter |
|DiffuseFilter |
|DisplaceFilter |
|DissolveFilter |
|FieldWarpFilter |
|FlipFilter |
|KaleidoscopeFilter |
|MarbleFilter |
|MirrorFilter |
|OffsetFilter |
|PerspectiveFilter |
|PinchFilter |
|PolarFilter |
|RippleFilter |
|RotateFilter |
|ScaleFilter |
|ShearFilter |
|SphereFilter |
|SwimFilter |
|TileImageFilter |
|TwirlFilter |
|WarpFilter |
|WaterFilter |
|===

=== Effects Filters

[cols="6,1",options="header"]
|===
|Filter |New

|BlockFilter |
|BorderFilter |
|ChromeFilter |
|ColorHalftoneFilter |
|CrystallizeFilter |
|EmbossFilter |
|FeedbackFilter |
|HalftoneFilter |
|LightFilter |
|NoiseFilter |
|PointillizeFilter |
|ShadowFilter |
|ShapeFilter |
|StampFilter |
|WeaveFilter |
|===

=== Texturing Filters

[cols="6,1",options="header"]
|===
|Filter |New

|BrushedMetalFilter |
|CausticsFilter |
|CellularFilter |
|CheckFilter |
|FBMFilter |
|FillFilter |
|FlareFilter |
|FourColorFilter |
|GradientFilter |
|PlasmaFilter |
|TextureFilter |
|ScratchFilter |
|SmearFilter |
|SparkleFilter |
|WoodFilter |
|===

=== Blurring & Sharpening Filters

[cols="6,1",options="header"]
|===
|Filter |New

|BlurFilter |
|BoxBlurFilter |
|BumpFilter |
|ConvolveFilter |
|DespeckleFilter |
|GaussianFilter |
|GlowFilter |
|HighPassFilter |
|LensBlurFilter |
|MaximumFilter |
|MedianFilter |
|MinimumFilter |
|MotionBlurFilter |
|OilFilter |
|RaysFilter |
|ReduceNoiseFilter |
|SharpenFilter |
|SmartBlurFilter |
|UnsharpFilter |
|VariableBlurFilter |
|===

=== Edge Detection

[cols="6,1",options="header"]
|===
|Filter |New

|DoGFilter |
|EdgeFilter |
|LaplaceFilter |
|===

=== Transitions

[cols="6,1",options="header"]
|===
|Filter |New

|BlurTransition |
|GradientWipeFilter |
|===

=== Alpha Channel Filters

[cols="6,1",options="header"]
|===
|Filter |New

|OpacityFilter |
|PremultiplyFilter |
|UnpremultiplyFilter |
|===

=== Miscellaneous Filters

[cols="6,1",options="header"]
|===
|Filter |New

|CompoundFilter |
|IteratedFilter |
|===


== License

MIT. See link:LICENSE[LICENSE].
